### PR TITLE
Hanabi improvements 2

### PR DESCRIPTION
**Pull request by andrejak**
- should fix win condition
- address Tom's comment on the colour type
- include a commit that I somehow forgot to push to last PR that indicates the current player more obviously
- indicate token loss/gain more clearly with colour animation
- reorganize discard pile (separate columns for colours)
- draw card into the played position, not to the right
- change font
- make everything a bit more mobile friendly (not perfect but should be playable)

Next: animating/highlighting cards to indicate what happened.

### CODE REVIEW

**Comment by tdawes** [comment]
Actually, my only comment would be that I have been playing with the browser occupying half my screen (so that I could have a video room open in the other) and this makes it overflow a bit - I can fix it by zooming out, which is probably good enough since I can't think of a better layout.

**Comment by andrejak** [comment]
Good point, same. It fits on half my screen now, let me know if it still doesn't on yours!

**Comment by tdawes** [comment]
Still overflows a little, when there are lots of players or lots of discarded cards, but I think that's fine

**Comment by tdawes** [comment]
Looks like it fits in about 2/3rds of my screen at 100% - that should be fine for playing.

**Pull request merged**
